name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Private project

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core package
  firebase_core: ^2.23.0
  cloud_firestore: ^4.14.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  shared_preferences: ^2.2.2  # Local storage for user preferences


  # Cupertino icons for iOS styling
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets here if needed
  assets:
    - assets/
  #   - images/example.png

  # Add custom fonts here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
